version: "3"
services:
  postgres:
    image: postgres:14
    container_name: ecommerce_db
    restart: always
    env_file: .env 
    volumes:
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init.sql
      - ecommerce_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  generator:
    build: ./generator
    container_name: data_generator
    restart: always
    depends_on:
      - postgres
    env_file: .env  

  redis:
    image: redis:5.0-alpine
    restart: always

  redash-postgres:
    image: postgres:14
    container_name: redash_internal_db 
    # env_file: .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${REDASH_INTERNAL_PASSWORD}
      POSTGRES_DB: ${REDASH_INTERNAL_DB}
    volumes:
      - redash_pg_data:/var/lib/postgresql/data

  server:
    image: redash/redash:10.1.0.b50633
    command: server
    ports:
      - "5000:5000"
    depends_on:
      - redash-postgres
      - redis
    env_file: .env 

  scheduler:
    image: redash/redash:10.1.0.b50633
    command: scheduler
    depends_on:
      - redash-postgres 
      - redis
    env_file: .env

  worker:
    image: redash/redash:10.1.0.b50633
    command: worker
    depends_on:
      - redash-postgres 
      - redis
    env_file: .env
    environment:
      PYTHONUNBUFFERED: 0  
      QUEUES: "queries,scheduled_queries,celery,default"

volumes:
  ecommerce_pg_data:
  redash_pg_data: